### ISSUE TITLE
설정값 관리 

### ISSUE THREAD

**Issue by JSPARK113** [Moons08/personal-finance-manager#17]
암호, 시크릿 키 등을 숨길 수 있는 설정파일, 클래스 등의 생성

참고문서:
https://mingrammer.com/ways-to-manage-the-configuration-in-python/

**Comment by Moons08** [comment]
이중에서 몇번으로 가나요?

**Comment by JSPARK113** [comment]
난 2번이 익숙한데.. 논의해서 정합시다
