### ISSUE TITLE
README에 최초 DB설정 내용 추가

### ISSUE THREAD

**Issue by JSPARK113** [Moons08/personal-finance-manager#18]
- postgresql 설정: db 생성 및 사용자 생성
  - `create database sampledb`
  - `create user sampleuser with password samplesecret`

- `$ python manage.py migrate` 실행

**Comment by Moons08** [comment]
요거는 `docker-compose.yml` 에 있긴한데, 필요할까?

**Comment by JSPARK113** [comment]
내가.. 도커를 안쓰고 서버를 켜가지고...😅 도커 안쓰고 환경켜는거도 리드미에 추가해도 괜찮을거같아서

**Comment by Moons08** [comment]
그렇긴하지만... 도커합시다 도커...

**Comment by JSPARK113** [comment]
최초에만 `migrate` 실행
